#!/bin/sh -e

#For debugging uncomment these two lines
set -x
echo $*

APP_NAME=${project.artifactId}

mkdir -p ${data.folder.location} || true
chown -Rf ${project.artifactId}:${project.artifactId} ${data.folder.location}

mkdir -p ${log.folder.location} || true
chown -Rf ${project.artifactId}:${project.artifactId} ${log.folder.location}

mkdir -p ${index.folder.location} || true
chown -Rf ${project.artifactId}:${project.artifactId} ${index.folder.location}

# Database command safe to run both on install and upgrade
echo "Creating ${project.artifactId} mysql database and user with permissions to access all trialslink_db schemas"
mysql -u root -e "CREATE DATABASE IF NOT EXISTS trialslink_db DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci; GRANT ALL  ON trialslink_db.* TO 'trialslink'@'localhost' IDENTIFIED BY 'tr14lzl1nk'; FLUSH PRIVILEGES;"

# Move service unit file from /tmp to /etc/systemd/system
mv /opt/$APP_NAME/$APP_NAME.service /etc/systemd/system/$APP_NAME.service || true
chmod 664 /etc/systemd/system/$APP_NAME.service || true

# Notify systemd that a new file has been added
systemctl daemon-reload || true

# Ensure service is started at boot
systemctl enable $APP_NAME.service || true

# Restart service
systemctl restart $APP_NAME || true